scylladb/gocql

- AUTHORS
- README.md
- conn.go
- internal/murmur/murmur_appengine.go
- internal/murmur/murmur_unsafe.go
- marshal.go
- policies.go
- policies_test.go
- session.go
- token.go
- topology.go
- topology_test.go
- tuple_test.go
Sync with upstream gocql/gocql using merge instead of rebase.
> Merged upstream into master

- README.md
Added training section to Readme file
> added training section with links to Scylla University

- scylla.go
> Closing connections deadlock fix

- session.go
On `connConfig` error session object is not closed so partially created resources are leaking, for instance `flusher` goroutine created by `newEventDebouncer`.
> session: fix resource leak on some errors

- conn.go
> scylla: add com.scylladb.auth.TransitionalAuthenticator to approvedAuthenticators

- AUTHORS
- cassandra_test.go
- cluster.go
- conn.go
- conn_test.go
- connectionpool.go
- control.go
- doc.go
- docker-compose.yml
- events.go
- events_test.go
- filters.go
- go.mod
- go.sum
- helpers.go
- helpers_test.go
- host_source.go
- integration.sh
- logger.go
- lz4/go.mod
- lz4/go.sum
- lz4/lz4.go
- lz4/lz4_test.go
- metadata_cassandra.go
- metadata_cassandra_test.go
- metadata_scylla.go
- policies.go
- session.go
- session_test.go
- topology.go
This merges all upstream changes up to 9a3953d.
> Merge upstream

- AUTHORS
- README.md
- cassandra_test.go
- conn.go
- control.go
- control_ccm_test.go
- dial.go
- doc.go
- events.go
- host_source.go
- host_source_test.go
- internal/ccm/ccm.go
- marshal.go
- marshal_test.go
- query_executor.go
- session.go
Merge upstream changes as of gocql v1.5.2.
> Merge upstream changes (gocql v1.5.2)

- scylla.go
Previously the check was always based on `p.conns[0]`, but there is a posibility that it is nil and it should be checked. The check should be based on not nil connection.
This PR introduces searching for first not nil connection and checking tablet-awareness based on this connection.
Fixes: https://github.com/scylladb/scylla-bench/issues/134.
> Fix checking if tablets should be used in scyllaConnPicker Pick

- cassandra_only_test.go
- exec_test.go
- host_source.go
- integration_cassandra_only_test.go
- internal/murmur/murmur_appengine.go
- internal/murmur/murmur_unsafe.go
- metadata_cassandra.go
- metadata_cassandra_test.go
- metadata_scylla.go
- metadata_scylla_test.go
- recreate.go
- recreate_test.go
- scylla.go
- scylla_shard_aware_port_integration_test.go
- scylla_shard_aware_port_mocked_test.go
- session.go
> Fix files formatting

- cassandra_test.go
- session.go
It is possible that empty response from nodes can confuse driver make it producing partial results.
To ensure it is not happening we need to test this scenario.
This is test for scenario outlined in https://github.com/scylladb/gocql/issues/180
> Have a test to make sure paging feature works properly with allow filtering queries

- lz4/go.mod
- lz4/go.sum
Closes https://github.com/scylladb/gocql/issues/160
> Update l4z libraries

- session.go
Previously in gocql there was no mechanism to retry the session detail fetch, and there is a need for it because tracing details are stored asynchronously. Other drivers have it e.g., python-driver and scylla-rust-driver. 
This commit adds new logic to be able to configure number of fetch attempts and intervals between these attempts. This fixes flaky tablets integration test.
Refs: #227
> Add logic to retry fetching trace info

- internal/tests/serialization/mod/custom.go
- marshal.go
- tests/serialization/marshal_19_list_set_v2_corrupt_test.go
- tests/serialization/marshal_19_list_set_v2_test.go
- tests/serialization/marshal_19_list_set_v3_corrupt_test.go
- tests/serialization/marshal_19_list_set_v3_test.go
Changes:
*Added marshal tests for `list`, `set` `cql types`
*Added `gocql.NewCollectionType` function to create `CollectionType`
> Add `list`, `set` marshal tests

- debounce/simple_debouncer_test.go
Fix https://github.com/scylladb/gocql/issues/328
Test can stuck at:
```
goroutine 23 [runnable]:
runtime.Gosched()
/opt/hostedtoolcache/go/1.23.2/x64/src/runtime/proc.go:353 +0x14
github.com/gocql/gocql/debounce.waitTillChannelIsEmpty(...)
/home/runner/work/gocql/gocql/debounce/simple_debouncer_test.go:53
github.com/gocql/gocql/debounce.TestSimpleDebouncer.func3(0xc0000b09c0)
/home/runner/work/gocql/gocql/debounce/simple_debouncer_test.go:41 +0x2a5
```
Due to fact that:
```
startedCh <- struct{}{}
go d.Debounce(fn)
go d.Debounce(fn)
```
Could be executed before debouncer starts first call execution.
> fix(simple_debouncer_test): make sure first call is picked up before making more calls

- conn.go
- conn_test.go
> Extract getSchemaAgreement to the separate function and unit test it against zero-token node

- control.go
- metadata_scylla.go
> Invalidate tablets for dropped keyspace/table on control connection reconnect

- frame.go
Change the if condition to a rarer case
> <framer> optimization `setLength(...)`

- frame.go
- marshal.go
Makes different functions for cases `-2`,`-1`,`n`
> <framer> optimization `appendInt(...)`

- frame.go
Changes:
* removes unnecessary error check
* removes unnecessary embedding in a `copyBytes` function
* makes reading bytes for `CustomPayload` with copying from buffer
> <framer> optimization `readBytes()`

- control.go
Following change:
1. Refactor code for the sake of clarity
3. Fix possible nil error
> Fix control connction reconnection

- session.go
It is unlikely, but in sake of stability it is better to just log a warning
> Fix possible panic when applied key is not bool

- session.go
Due to missing `break` driver reconnects even if connection was succcessfully esstablished when session is being initialized.
> Do not reconnect on success

- conn.go
- tablets.go
Based on https://github.com/scylladb/gocql/pull/464
`TabletInfo` should be constructed once and then to be used in read only mode.
To make it happen and not to export read only fields of `TabletInfo` we need to have another struct with exported fields to be converted to `TabletInfo` when all the information is filled it.
Also will help to decouple tablets from `gocql`.
Related to: https://github.com/scylladb/gocql/issues/469 and https://github.com/scylladb/gocql/issues/470
> Tablets: introduce tabletinfo builder

- .github/workflows/bench-tests.yml
- Makefile
- internal/tests/common.go
- internal/tests/rand.go
- tablets/tabets_utils_test.go
- tablets/tablet_utils.go
- tablets/tablets.go
- tablets/tablets_bench_test.go
- Benchmarks `FindTablets`, `FindTabletForToken`, and `AddTabletToTabletsList` methods
- Adds performance tests for `CowTabletList` under various workloads:
* Parallel and single-threaded execution
* Prepopulated vs empty state
* Scenarios with host, table, and keyspace removal operations
- Uses randomized token and replica generation to simulate real-world usage
Fixes: https://github.com/scylladb/gocql/issues/471
> Tablets: Add bench tests
