scylladb/gocql

README.md

I've added information about how to use this fork with go modules.

scylla: Add go mod replace info to readme

---

.github/issue_template.md

As a fork serving Scylla users, we should not assume they are using Cassandra.

issue-template: ask about Scylla version

---

scylla.go

We simply log and ignore a connection that does not have the proper sharding info attached.
Fixes: #10

scylla: avoid panic when removing a non-sharded connection from the pool

---

scylla.go

Keep a list of excess connections and only close these when we have connections to all the shards.

scylla: lazily close excess connections once equilibrium is reached.

---

token.go
token_test.go

The driver silently replaced the current token with the closest one
from the token ring that it could find. This worked well enough
to route the request to the correct host but to pick the right shard
we need the actual token for the qiven query.

scylla: ensure we use the correct token to determine shard

---

policies.go
policies_test.go
token.go
token_test.go

`tokenAwareHostPolicy` always selects a primary replica of a token.
When using `tokenAwareHostPolicy` backed by `dcAwareRR`, for tokens
with primary replica in a different DC, this results in selecting
a RANDOM host in a given DC.
This bug was previously fixed in commit
scylladb/gocql@39cb625a5f6c96219b1f810cce34b14d034b3681 and
gocql/gocql@ec4793573d1447b6f92a1b359a0594566fad9d0e,
but was reintroduced in the scylla branch by commit
scylladb/gocql@1469a13d9cdd60e2bec9ea38eb7b3bcd4c78d5de.
The test for token aware policy is updated so that
the regression does not happen again.

Fix tokenAwareHostPolicy host selection

---

go.mod

We advise users to replace the module with:
go mod edit -replace=github.com/gocql/gocql=github.com/scylladb/gocql@v1.2.0
However this fails with:
go: github.com/scylladb/gocql@v1.2.0: parsing go.mod: unexpected module path "github.com/gocql/gocql"
go: error loading module requirements
Since go mod expects github.com/scylladb/gocql module and finds a
different name.
This PR fixes that.

gocql: match the module name with replace path

---

policies_test.go

This test uses a more common network topology strategy with
replication factor 2 in each DC.

Add another test for TokenAware+DCAware host selection policy

---

policies.go
policies_test.go

The first commit adds a reproducer test for https://github.com/gocql/gocql/issues/1274 which runs for 100ms. I'll let you decide if you want to include it or not.
The second commit is almost identical to https://github.com/gocql/gocql/pull/1332

Fix for gocql/gocql issue 1274

---

AUTHORS
policies_test.go

This commit fixes error:
```
type *tokenAwareHostPolicy has no field or method keyspaces
```
which was introduced with 47e14727 after merging https://github.com/scylladb/gocql/pull/22
Commit 9867ae96 removed field used in the test and this change later was
not reflected during ongoing merges.

policies: Fix getting replicas in TestHostPolicy_TokenAware_DCAwareRR2

---

marshal.go
marshal_test.go

Map collections with blob values weren't marshalled into
map[string]interface{}.
This patch allows to store []byte in such map.

marshal: blob support for map[string]interface{}

---

recreate.go
testdata/recreate/index_golden.cql
testdata/recreate/keyspace_golden.cql
testdata/recreate/materialized_views_golden.cql
testdata/recreate/secondary_index_golden.cql
testdata/recreate/table_golden.cql
testdata/recreate/udt_golden.cql

Table fields where misaligned with table options.
MV fields where used different indentations, now it's aligned with rest.
Removed first empty line.
Fixes #46

recreate: fixed formatting of CQL output

---

conn.go
scylla.go
scylla_test.go

Get rid of unnecessary repeated parsing of "SCYLLA" connection
options.
Parse only once and save in the connection object as
`scyllaSupported` field.
Save raw "supported" field for debugging purposes.
Fix `mockConn` function in scylla tests to accept int as shard
number and initialize `scyllaSupported` field directly.
Tests: unit
Signed-off-by: Pavel Solodovnikov <pa.solodovnikov@scylladb.com>

Parse scyllaSupported metadata once

---

cluster.go
frame.go
session.go
session_test.go

- SerialConsistency values are moved to Consistency
- All SerialConsistency fields are changed to Consistency
- API is preserved, and SerialConsistency is alias type
Fixes #58

Add SerialConsistency to Consistency

---

README.md
cluster.go
conn.go
conn_test.go
connectionpool.go
connpicker.go
frame.go
host_source.go
scylla.go
scylla_shard_aware_port_common_test.go
scylla_shard_aware_port_integration_test.go
scylla_shard_aware_port_mocked_test.go
scylla_test.go

In commit [1572b9e41cd02e8b676404ba72a549398d281a66](https://github.com/scylladb/scylla/commit/1572b9e41cd02e8b676404ba72a549398d281a66), Scylla gained
support for so-called "shard-aware" ports. These ports support the same
Cassandra native protocol as the regular native transport ports.
However, unlike the regular ports, shard-aware ports allow the driver to
choose the shard that will handle the connection by choosing an
appropriate source port.
Currently, regular native transport ports employ a load-balancing
strategy that assigns, for an incoming connection, the shard that has
the least amount of connections assigned. Until now, the driver worked
by opening new connections until a single connection per shard is
established. When a connection to an already connected shard is opened,
it …

Add support for establishing per-shard connections using Scylla shard-aware ports

---

metadata_scylla.go
policies.go
query_executor.go
scylla.go
scylla_cdc.go
scylla_test.go
session.go
token.go
token_test.go

In https://github.com/scylladb/scylla/commit/6f1a8cfeeaaf775fd4935c22644b276b5780c6b8, Scylla started using a custom partitioner for CDC log tables. This partitioner, similarly to Murmur3Partitioner, generates int64 tokens, but uses a different algorithm to calculate them. This causes the drivers which are unaware of the custom partitioner to wrongly choose coordinators for prepared queries to CDC log tables, rendering token- and shard-awareness useless.
This PR implements support for the CDC custom partitioner, which fixes token- and shard-awareness for CDC log tables.
I did the following manual tests (3 node cluster, 4 shards, keyspace with RF=1, single table with cdc enabled):
- Read from a cdc log table with tracing enabled. Without this PR, tracing shows that the coordinator had to …

Add support for the CDC partitioner

---

cass1batch_test.go
conn.go
policies_test.go
session.go
session_test.go

Query and Batch can be copied and we shouldn't modify them directly
during execution, this was not the case previously as lwt and
partitioner fields could be accessed by multiple goroutines when the
driver was speculatively executing the query.
Because Query and Batch are copied (and a few exported methods have
value receiver), we cannot embed the mutex directly into Query and
Batch and separate struct needs to be allocated.
Fixes: https://github.com/scylladb/gocql/issues/65

Fix data race accessing lwt/partitioner in Query/Batch

---

README.md
cluster.go

Adds information about `NumConn` not being used when working with Scylla cluster to README.md and `NumConn`'s comment.
Fixes #68

Document that NumConns has no effect when working with Scylla

---

.github/workflows/main.yml
common_test.go
docker-compose.yml
testdata/config/scylla.yaml

It allows to run tls and non-tls test suits without tearing up and down test environment

Open both encrypted and unencrypted Scylla in integration suite

---

cluster.go

This change is to make maintanance easier.
With comments above the fields, each field is indented separately,
so we can insert new fields into the struct and update the documentation
comments without gofmt reformating the whole struct.
This should reduce diffs in commits and minimize conflicts when
merging to forks.

Reformat ClusterConfig to have doc comments above fields

---

cluster.go
conn.go
connectionpool.go
connpicker.go
dial.go
host_source.go
scylla.go

There are multiple use cases where the Dialer interface is not
sufficient.
When using TLS, users need to control also TLS context per host.
For example, host certificates might be either UUID in common name,
some hostname, IP address per host, etc.
Hosted instances or instances deployed in Kubernetes cluster tend
to be behind proxies. A proxy might use TLS server name indication
to identify which database host to connect to.
This commit adds Scylla-specific ShardDialer interface,
so that HostDialer works with shards as well.

Add HostDialer interface

---

scylla.go
scylla_test.go

It turns out that shard awareness is a great optimisation but in case of extremely high load, the original behaviour of picking the least busy connection performs better. This is because original algorithm load-balances coordinator work more evenly among shards.
This PR brings back the old, non shard aware behaviour when the selected connection that targets the right shard is more than 50% busy and there is another connection that's at least 20% less busy. Then we use the least busy connection instead of the one that connects to the right shard.

Merge shard awareness with original behaviour

---

events.go

For the moment we have unsafe coding where we try to use 'host' object
before checking the success of it's 'get' operation.
When a Scylla node gets forcibly terminated we have a race condition
and to some probability to get the following panic:
```    
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x632814]
goroutine 1723 [running]:
github.com/gocql/gocql.(*HostInfo).HostID(0xc0001500b8)
%full-path%/gocql@v1.7.1/host_source.go:271 +0x34
github.com/gocql/gocql.(*Session).handleRemovedNode(
0xc000150000, {0xc0134c10d8, 0xc0093d69b0, 0xa}, 0x45264d)
%full-path%/gocql@v1.7.1/events.go:243 +0x5f
github.com/gocql/gocql.(*Session).handleNodeEvent(
0xc000150000, {0xc01701a000, 0x1, 0x43e305}) …
```

Fix nil pointer dereference in event handling node removal

---

scylla.go

The field is not used anywhere.

Remove scyllaConnPicker.dialer

---

host_source_scylla.go
scyllacloud/config.go
scyllacloud/config_test.go
scyllacloud/hostdialer.go
scyllacloud/hostdialer_test.go

When host information was missing, driver used resolved IP address as TLS.ServerName. 
Instead it should connect to Server specified in ConnectionConfig and use NodeDomain as SNI.

Use ConnectionConfig values when establishing session to initial contact point

---

.github/workflows/main.yml
scylla_test.go

`go vet` and `go test` without any package arguments runs only
on the go files in the repo root directory. It should run on all
non-vendored packages.
Fixes following go vet failure:
* `./scylla_test.go:180:4: call to (*T).Fatal from a non-test goroutine`

Run go vet and tests in all subpackages in CI

---

errors.go
frame.go
scylla.go
scylla_test.go

Since recently, Scylla has begun to support a new CQL error type, RateLimitError. For this error to be recognised by the driver properly, a proper negotiation is needed. It was implemented similarly to the already-present LWT optimisation extension negotiation.

rate limit CQL extension support

---

cluster.go
conn.go
internal/streams/streams.go

Before this change, a connection had a hardcoded maximum number of streams. Since this value was so large (32768 for CQL v3+) this essentially meant an unbound concurrency.
This commit allows a user to configure this parameter by a newly added MaxRequestsPerConn option.
The "MaxRequestsPerConn" naming was chosen to be very general deliberately to allow us to safely introduce a more advanced behavior in the future: where the concurrency limiting happens not at a IDGenerator level and an additional client-side queue is introduced for requests to wait to be sent to Scylla (in addition to inflight requests queue).
This commit deliberately does not change the defaults as to be non-pessimizing for the users.
Fixes #112

Add configurable MaxRequestsPerConn cluster param

---

conn.go
version.go

The main module name is stored in a `const` in `version.go`.
The replaced module name and the version are fetched from the binary runtime information, where it comes from GitHub metadata (release tag).
Credits to @zimnx for this idea!
I've tested this manually using my fork. The version has shown correctly in `system.clients`.
Fixes: #119

Advertise driver name & version in STARTUP message

---

docker-compose.yml

Due to the #126, we need to increase memory limit for scylla to avoid prepared stmt eviction during tests

fix(docker-compose.yaml): increase memory limit to avoid hitting #126

---

.github/workflows/main.yml
docker-compose.yml
integration.sh

As per Docker documentation:
> From July 2023 Docker Compose V1 stopped receiving updates. It’s also no longer available in new releases of Docker Desktop.
Therefore, the first patch replaces all uses of Docker Compose V1 (`docker-compose` command) with Docker Compose V2 (`docker compose` command) and changes installed version of Docker Compose in main.yml.
This gives a possibility to replace manual checking the health of the containers with healthchecks and using `--wait` flag in `docker compose`. `--wait flag` makes Docker wait for all healthchecks to be in "healthy" state. Since docker-compose.yml files in this repository use `cqlsh` to determine the health of a container, this means that Docker will wait for all nodes of the cluster to be fully bootstrapped and their CQL port ready. …

Add healthchecks, switch from Docker Compose V1 to V2

---

go.mod

Retract `v1.8.0`, `v1.8.1`, `v1.9.0`, `v1.10.0` - tags mistakenly taken from `kiwicom/gocql`, which are not actual releases made in `scylladb/gocql`.
Even though those tags were removed from `scylladb/gocql` (see #110), some Go module mirrors have already fetched them:
```
$ go list -m --versions github.com/scylladb/gocql
github.com/scylladb/gocql v1.0.0 v1.0.1 v1.0.2 v1.0.3 v1.0.4 v1.1.0 v1.2.0 v1.2.1 v1.3.0-rc.1 v1.3.0 v1.3.1 v1.3.2 v1.3.3 v1.3.4 v1.4.0 v1.4.1 v1.4.2 v1.4.3 v1.5.0 v1.6.0 v1.7.0 v1.7.1 v1.7.2 v1.7.3 v1.8.0 v1.8.1 v1.9.0 v1.10.0
```
As we can't control those mirrors, they will always return an incorrect version of gocql, even if we release "new" `v1.9.0`, `v1.10.0`.
Subsequent to merging of this patch, version `v1.11.0` of `scylladb/gocql` will be released.
Fixes #132

Retract tags taken by mistake from kiwicom/gocql

---

cluster.go
cluster_test.go
conn_test.go

Merge upstream changes as of gocql v1.6.0.
Fixes: #143

Merge upstream changes (gocql v1.6.0) 

---

control.go

Previously if connection to the node failed, information about that was logged, but it was not handled in any other way. The node down handling has had been there, but it has had been deleted in https://github.com/gocql/gocql/commit/56d43d598ab6e840b2a49c9e1bedb1c8210f3472.
If during restart the resources assigned to node change, the driver does not update this. That could lead to outdated information about shards.
In Scylla without this when restarting node with increased assigned resources happen, there was a panic due to wrong number of shards.
I added previously removed marking node as down.
Fixes: https://github.com/scylladb/gocql/issues/145

Mark node as down if unable to dial control conn

---

.github/workflows/main.yml
docker-compose.yml
recreate.go
recreate_test.go
testdata/recreate/aggregates.cql
testdata/recreate/aggregates_golden.cql

Previously strings used to parse `CREATE FUNCTION` and `CREATE AGGREGATE` had errors, now it is fixed.
I also added testcase in `recreate_test.go` for testing `aggregateToCQL`.
Fixes: https://github.com/scylladb/gocql/issues/130

Fix aggregate bug

---

.github/workflows/main.yml
common_test.go
conn.go
connectionpool.go
connpicker.go
docker-compose.yml
frame.go
host_source.go
integration.sh
metadata_scylla.go
policies.go
query_executor.go
ring.go
scylla.go
scylla_test.go
session.go
tablet_integration_test.go
tablet_test.go

This PR introduces changes to the driver that are necessary for shard-awareness and token-awareness to work effectively with the tablets.
Now if driver send the request to the wrong node/shard it will get the correct tablet information from Scylla in `custom_payload`. It uses this information to obtain target replicas and shard numbers for tables managed by tablet replication. 
I also added parsing `TABLETS_ROUTING_V1` extension. In order for Scylla to send the tablet info, the driver must tell the database during connection handshake that it is able to interpret it. It was implemented similarly to the already-present LWT optimization extension negotiation.
The metadata for tablets are provided to the user.
To test this change I created both integration and unit tests.
Fixes: #155

Introduce support for tablets

---

common_test.go

https://github.com/scylladb/scylladb/pull/16364 changed the way keyspace should be initialize to use tablets.
This PR updates the way that keyspace with tablets is initialized.

Update CI to use new way of initializing keyspace with tablets

---

cluster.go
conn.go
control.go

Now we are sending OPTIONS message on every connection every 5 seconds.
This PR changes that to 30 seconds (this is the number used in python-driver - https://github.com/scylladb/python-driver/blob/7cdc1ca25ffa2194a0772e46ccd89645f8514c1b/cassandra/cluster.py#L893) and enables the keepalive - with 15s by default (matches Golang's default).
Fixes: #162

Send heartbeat OPTIONS message less frequent and enable keep alive

---

conn.go

When LWT optimization was implemented in gocql (https://github.com/scylladb/gocql/pull/49), all `newFramer` calls were replaced with `newFramerWithExts` calls.
Previously, during the upstream merging the code using `newFramer` was added (https://github.com/scylladb/gocql/pull/109) and it was forgotten to replace it with `newFramerWithExts`. That way, the `flagLWT` field was set to `0` by default, causing the driver to consider every query executed as a LWT query.
The issue was not immediately noticed because the only difference in behavior occurs when we want to use `ShuffleReplicas()` in `TokenAwareHostPolicy`.
This PR fixes the issue by replacing `newFramer` with `newFramerWithExts`.
Fixes: #174

Use `newFramerWithExts` instead of `newFramer` to utilize protocol extensions

---

connectionpool.go
connpicker.go
host_source.go
internal/streams/streams.go
policies.go
scylla.go

The java driver has the feature to automatically avoid slow replicas by doing simple heuristics (https://github.com/scylladb/java-driver/blob/scylla-4.x/core/src/main/java/com/datastax/oss/driver/internal/core/loadbalancing/DefaultLoadBalancingPolicy.java#L104). This is one of the key feature to have a stable latency.
This PR adds additional field in tokenAwareHostPolicy to control if the feature is enabled and what is the maximum in flight threshold.
If feature is enabled driver sorts the replicas to first try those with less than specified maximum in flight requests.
Fixes: #154

Add LOAD_BALANCING_POLICY_SLOW_AVOIDANCE funtionality

---

scylla.go

`net.Dialer` makes golang runtime run `bind` if `LocalAddr` is not nil, even if address is `":0"`.
https://github.com/golang/go/blob/master/src/net/sock_posix.go#L109-L117
Calling `bind`, due to it's nature, marks obtained port as non-reusable, which limits number of possible connections/sessions.
It is inevitable for `share-aware` connections, since we need to pick the port, but for `none-shard-aware` connections it must be avoided.
Closes #179

fix(dealer): make net.Dialer not to bind to reuse ephimeral ports

---

.github/workflows/main.yml
docker-compose.yml
testdata/config/scylla.yaml

Previously scylla integration tests used scylla 5.2.9 and tablet tests used `scylladb/scylla-nightly`.
This PR changes scylla version to `scylladb/scylla:5.4.6` for node used to integration test and to fixed version of scylla-nightly for tablet tests.

Bump scylla version to 5.4.6 and use fixed version for all of the nodes

---

connectionpool.go
connpicker.go
host_source.go
metadata_scylla.go
policies.go
query_executor.go
scylla.go
scylla_cdc.go
scylla_test.go
session.go
token.go
token_test.go
topology.go

currently private interface `token` directly or indirectly present in lot's of interfaces and therefore makes them unimplementable: `SelectedHost`, `ExecutableQuery`, `HostSelectionPolicy`, `NextHost`
To fix it we need to make all parts of interfaces be public
Closes #183

Make public interfaces implementable

---

host_source.go
policies.go
policies_test.go

Addresses [issue](https://github.com/gocql/gocql/issues/1757) from [gocql/gocql](https://github.com/gocql/gocql/)
Reopening of a https://github.com/scylladb/gocql/pull/182
`cowHostList` uses `HostInfo.Equal` to confirm host uniqueness, which relies on `ConnectAddress.Equal`.
As result `cowHostList` does not allow to have different hosts with same `ConnectAddress`.
It breaks cases like accessing cluster via [tcp](https://github.com/gocql/gocql/issues/1757) or [ssl](https://github.com/gocql/gocql/issues/1452) proxy

Fix cowHostList can't have hosts with same `ConnectAddress`

---

marshal.go

There has been a mistake - Duration type consists of months, days and nanoseconds. This PR makes a quick fix.

Rename invalid variable name in encVints from seconds to days

---

policies.go

There is no need to have a lock there, `cowHostList` does copy on write, which makes it safe to use the list without locking it.

Remove unnecessary cowHostList lock

---

host_source.go

I know that there is comment by @zariel to reduce locking.
I didn't thoroughly refactor the code, but I found fast and cheap optimization in functions `(*HostInfo).HostName` and `(*HostInfo).HostNameAndPort`.
In our case of https://github.com/scylladb/gocql/pull/164 `(*HostInfo).HostName` leads to spending a lot of time in Lock...
Also in `QueryObserver` and `BatchObserver` we calls public methods of `HostInfo` (`HostName` ,  `HostNameAndPort`) for metrics and we have a lot of mutex locks.

HostInfo: reduce mutex.Locks

---

host_source.go
tablet_test.go

`TabletInfo` attributes are getting written only once, on its initialization.
It has nothing to mitigate with locks

Remove unnecessary locks from TabletInfo

---

policies.go

Main goal of this PR is to make `tokenAwareHostPolicy.Pick` code less convoluted.
But there are little functional changes:
Before this PR hosts from tablets are not being shuffled 
There are three host information sources: tablets, meta and tokenring, 
Before this PR if tables returned no hosts for given token, in certain cases code did not consider meta or tokenring.
And same for meta, it did not consider tokenring.
After this PR, it starts goes through tablets, meta and tokenring, if current host sources yield no hosts it proceed to next one.
There was locking done on `cowTabletList` at `t.tablets` to read tablets, but since `cowTabletList` solves parallel access issue through COW, it is not needed.

Simplify tokenAwareHostPolicy.Pick

---

conn.go
scylla.go
session.go

Removes unnecessary `Conn.mu` locking on accessing `tabletsRoutingV1` flag.
`Conn.mu` is overused, less it is used less contention is yielded along with more performance.

Remove locks for tablets flag on Conn

---

policies.go
policies_test.go

Previously the driver would always failover to use replicas in the remote datacenters if there was no replicas available in local_dc when using `DC/RackAwareRoundRobinPolicy`. There was no control over it. This is not how the other driver handle it.
In python-driver there is an additional field in the `DCAwareRoundRobinPolicy` named `used_hosts_per_remote_dc` and it is 0 by default.
In java-driver 4.x there is also similar mechanism as in python-driver, there is a field `usedHostsPerRemoteDc`.
In rust driver there is `permit_dc_failover` option in the `DefaultPolicy`. If it is set to true driver can use replicas in dcs other than local. By default it is false.
This PR adds a field to `dc/rackAwareRR` to control if dc failover is permitted. To avoid breaking changes I decided not to change …

Add option to control if remote replicas should be used

---

policies.go

No functional changes only syntax sugar

Remove unnecessary negating

---

policies.go
policies_integration_test.go
policies_test.go
session.go

Previously there was no check if DC name provided in the policy (DCAware and RackAware) is correct. That could lead to e.g. making routing decisions based on the wrong DC name.
This PR introduces failing to connect if DC name is different in the topology than the one the user entered.
Fixes: #205

Add the datacenter name validation if provided

---

connectionpool.go
connpicker.go
query_executor.go
scylla.go
scylla_test.go
session.go

There is a code in gocql that selects another connection to a node if chosen connection is too busy (has less than half available stream ids).
We should not do this with LWT.

Do not choose less busy connection if query is LWT

---

tablet_integration_test.go

Time to time this test fails due to not obviouse reason 
To make it possible investigate the issue we need to drop more details when it happens
Failure example:
```
tablet_integration_test.go:72: expected queriedHosts to be (1) but was (0) instead
```

Make tablet test provide more details on failure

---

AUTHORS
doc.go
policies.go
policies_test.go
query_executor.go

RetryPolicy may want to return different decisions from `GetRetryType` depending on whether query is LWT or not - to prevent executing LWT on non-primary replica.
This is not possible with current interface, because `GetRetryType` doesn't know the query type.
This PR introduces new interface, `LWTRetryPolicy`. If configured retry policy also implements `LWTRetryPolicy`, then methods from `LWTRetryPolicy` will be called for LWT statements instead of methods from `RetryPolicy`.
There are alternative approaches to this issue:
- Introduce LWTRetryPolicy as another field in Session and Query: requires changes in user code.
- For LWT queries ignore GetRetryType and retry on the same host: it's less configurable

Add LWTRetryPolicy interface

---

metadata_scylla.go
metadata_scylla_test.go
recreate.go
recreate_test.go

No need to keep client-side logic which needs to be updated every time there is changes on server-side.
Closes https://github.com/scylladb/gocql/issues/195

Switch to use server side schema description for KeyspaceMetadata.ToCQL

---

cluster.go
conn.go
control.go
host_source.go
metadata_cassandra.go
metadata_scylla.go
schema_queries_test.go
session.go

Adds `USING TIMEOUT` clause to schema queries when applicable.
Uses the timeout defined by `MetadataSchemaRequestTimeout` option in `ClusterConfig`.
Fixes: #172 
Fixes: #157

Schema queries with configurable server-side timeouts

---

README.md

Closes https://github.com/scylladb/gocql/issues/180
Add docs for interator empesizing that user should not treat empty response as end of result set.

Add iterator docs

---

cluster.go
conn.go
version.go

Part of https://github.com/scylladb/scylla-drivers/issues/7
We want all drivers to report their names uniformly.

Expose driver name/version configuration on cluster config level and change default driver name

---

internal/streams/streams.go

Since offset is always truncated to s.numBuckets, atomic.Add could be used instead of atomic.Load + atomic.Swap

Simplify IDGenerator and reduce collission rate

---

marshal.go

Schemagen generates structs as [16]byte for uuid and timeuuid columns. 
when a time/uuid column has nil value, the switch case will not match with *[]byte and returns the following error:
`can not unmarshal X timeuuid into *[16]uint8`
to solve this we can change Schemagen, or add the case here. personally I belive changing Schemagen has more cost and mapping UUIDs to [16]byte is better than mapping to []byte.

Bug fix: Add matching case for unmarshalling nil uuid column

---

cluster.go
conn_test.go
policies.go
session.go

We would want to retry on initial connection to the cluster, in case if cluster is not ready yet.
This PR introduced new `InitialReconnectionPolicy` option to `ServerConfig`, by default it is `NoReconnectionPolicy`, to ensure old behavior.
Closes #230

Introduce initial reconnection policy

---

session.go

Currently it does not pick up error and fails with nil dereference.

Return operational error when IsOperation fails

---

session.go

Previously the condition deciding if tracing is ready was correct only for select queries, but for insert queries it was always false. Because of that there was a possiblility of quering control connection for tracing more times than it was needed.

Fix string condition in tracing

---

cluster.go
connectionpool.go
session.go

Let's expand cluster validation and move SSL initialization/validation to just before session is being created.

Expand cluster validation and move SSL initialization to the validation step

---

session.go

Go with the approach from `cqlsh` and check duration instead of activity to verify if trace is ready. 
Fixes: #242

Check duration to verify if trace is ready

---

cassandra_test.go
doc.go
session.go
session_test.go
tablet_integration_test.go
tracer.go
tracer_test.go

Reading of tracing info should be done asynchronously, otherwise enabling tracing will lead to query processing slow down. Current implementation of Tracer - traceWriter has this flaw and is actually not exactly useful, it just write custom formatted messages into a buffer.
This commit adds new implementation of Tracer - tracer which address that problems.
Fixes: #227

Add new API for tracing

---

conn.go
host_source.go
integration_test.go

Previously due to the wrong re-declarations of one variable error handling logic in `awaitSchemaAgreement` was broken. This code has always had the same result because the `err` in the condition was the error declared in the function definition not the one used in the for loop above.
https://github.com/scylladb/gocql/blob/master/conn.go#L1879-L1881
This PR fixes error handling as well as refactors some pieces of the code.
Fixes: #70

Refactor awaitSchemaAgreement logic

---

connectionpool.go
connpicker.go

i use this driver to interact with an apache Cassandra cluster : the [defaultConnPicker](https://github.com/scylladb/gocql/blob/c33cb5219995f721fc2978b01188f72cf879e3b5/connectionpool.go#L590-L595) is used
the application queries eventually fail with the error [`ErrNoConnections`](https://github.com/scylladb/gocql/blob/c33cb5219995f721fc2978b01188f72cf879e3b5/query_executor.go#L197), without any recovery
all connPicker connections eventually are set to `nil` by handling of sporadic network errors over time:
- `Conn.closeWithError` ([code](https://github.com/scylladb/gocql/blob/3a1e987b9cb437b62f85f190466926d9d84107fe/conn.go#L1158))
- `hostConnPool.HandleError` ([code](https://github.com/scylladb/gocql/blob/3a1e987b9cb437b62f85f190466926d9d84107fe/conn.go#L599-L600))
- …

Fix ErrNoConnections from defaultConnectionPicker.Remove code

---

cassandra_test.go
common_test.go
control_integration_test.go
keyspace_table_test.go
testdata/recreate/aggregates.cql
testdata/recreate/aggregates_golden.cql
testdata/recreate/index.cql
testdata/recreate/index_golden.cql
testdata/recreate/keyspace.cql
testdata/recreate/keyspace_golden.cql
testdata/recreate/materialized_views.cql
testdata/recreate/materialized_views_golden.cql
testdata/recreate/secondary_index.cql
testdata/recreate/secondary_index_golden.cql
testdata/recreate/table.cql
testdata/recreate/table_golden.cql
testdata/recreate/udt.cql
testdata/recreate/udt_golden.cql

SimpleStrategy is getting depricated, as replacement is it recomended to use NetworkTopologyStrategy instead. 
This PR switches tests to use NetworkTopologyStrategy. Tests that are specifically targeting SimpleStrategy stays as they are.
Fixes: #217

Switch tests from SimpleStrategy to NetworkTopologyStrategy

---

cluster.go

As enabling skipping metadata can lead to correctness problems (https://github.com/scylladb/scylladb/issues/20860) it has to be disabled by default. 
This PR implements that change and adds a warning when someone enables this optimization.

Change default behavior with skipping metadata

---

marshal.go
marshal/tinyint/marshal.go
marshal/tinyint/marshal_utils.go
marshal/tinyint/unmarshal.go
marshal/tinyint/unmarshal_utils.go
marshal_2_tinyint_corrupt_test.go
marshal_2_tinyint_test.go

Fixed for `tinyint` type:
1.1. Was: marshals `""` - caused an error; unmarshals `nil data` into `"0"`.
2. `custom string` marshals and unmarshals was `not supported`, now `supported`.
3. `big.Int` marshals was `not supported`, now `supported`.
4. Also was fixed cases when marshal and unmarshal should an error, but currently we does not have a `corrupt test suite`.
Close issues for `tinyint`:
1) #246 
2) #243
3) #244
4) #250

Fix marshal tinyint

---

marshal.go
marshal/smallint/marshal.go
marshal/smallint/marshal_utils.go
marshal/smallint/unmarshal.go
marshal/smallint/unmarshal_utils.go
marshal_3_smallint_corrupt_test.go
marshal_3_smallint_test.go
marshal_test.go

Fixed for `smallint` type:
1.1. Was: marshals `""` - caused an error; unmarshals `nil data` into `"0"`.
2. `custom string` marshals and unmarshals was `not supported`, now `supported`.
3. `big.Int` marshals was `not supported`, now `supported`.
4. Also was fixed cases when marshal and unmarshal should an error, but currently we does not have a `corrupt test suite`.
Close issues for `smallint`:
1) #246 
2) #243
3) #244
4) #250

Fix marshal smallint

---

marshal.go
marshal/cqlint/marshal.go
marshal/cqlint/marshal_utils.go
marshal/cqlint/unmarshal.go
marshal/cqlint/unmarshal_utils.go
marshal_3_smallint_corrupt_test.go
marshal_4_int_corrupt_test.go
marshal_4_int_test.go
marshal_test.go
token_test.go

Fixed for `int` type:
1.1. Before: marshals `""` - caused an error; unmarshals `nil data` into `"0"`.
2. `custom string` marshals and unmarshals, before `not supported`, now `supported`.
3. `big.Int` marshals, before `not supported`, now `supported`.
4. Marshal data, which equal `math.MaxUint32`, into `uint32`, `uint64`, `uint`, return `error' before, now `no error`.
5. Unmarshal `data` with the length is different from `0` and `4`, did not return `error` before, now it returns `error'.
Close issues for `int`:
1) #246 
2) #243
3) #244
4) #250
5) #252

Fix `int` marshal, unmarshall

---

connectionpool.go
debounce/simple_debouncer.go
debounce/simple_debouncer_test.go
scylla_shard_aware_port_common_test.go

This PR introduces the mechanism to ignore request to call `pool.fill()` if there is already one call scheduled, but not being executed yet.
Fixes: #258

Start debouncing pool.fill() calls

---

marshal.go
marshal/bigint/marshal.go
marshal/bigint/marshal_utils.go
marshal/bigint/unmarshal.go
marshal/bigint/unmarshal_utils.go
marshal_5_bigint_corrupt_test.go
marshal_5_bigint_test.go
marshal_test.go

Fixed for `bigint` type:
1.1. Before: marshals `""` - caused an error; unmarshals `nil data` into `"0"`.
2. `custom string` marshals and unmarshals, before `not supported`, now `supported`.
3. `big.Int` marshals, before `not supported`, now `supported`.
4. Marshal data, which equal `math.MaxUint64`, into `uint64`, `uint`, return `error' before, now `no error`.
5. Unmarshall `data` with the length is different from `0` and `8`, did not return `error` before, now it returns `error'.
Close issues for `bigint`:
1) #246 
2) #243
3) #244
4) #250
5) #252

Fix `bigint` marshal, unmarshall

---

marshal.go
marshal/counter/marshal.go
marshal/counter/marshal_utils.go
marshal/counter/unmarshal.go
marshal/counter/unmarshal_utils.go
marshal_6_counter_corrupt_test.go
marshal_6_counter_test.go

Fixed for `counter` type:
1.1. Before: marshals `""` - caused an error; unmarshals `nil data` into `"0"`.
2. `custom string` marshals and unmarshals, before `not supported`, now `supported`.
3. `big.Int` marshals, before `not supported`, now `supported`.
4. Marshal data, which equal `math.MaxUint64`, into `uint64`, `uint`, return `error' before, now `no error`.
5. Unmarshall `data` with the length is different from `0` and `8`, did not return `error` before, now it returns `error'.
Close issues for `counter`:
1) #246 
2) #243
3) #244
4) #250
5) #252

Fix `counter` marshal, unmarshall

---

marshal/tinyint/marshal_utils.go
marshal/tinyint/unmarshal.go
marshal/tinyint/unmarshal_utils.go
marshal_2_tinyint_test.go

Chenges:
1. Unmarshal functions:
1.1. The double conversion of values has been removed in the functions of single reference values.
1.2. The condition `data == nil` moved after the condition `len(data)==0` in the functions of the double references values.
2. `EncReflect` function:
2.1. Removed unnecessary checks for `reflect.Int8` and `reflect.Uint8` kinds.
2.2. Makes the right value type in the error for `reflect.String` kind.

Fix marshal  `tinyint` - optimization

---

serialization/bigint/marshal_utils.go
serialization/bigint/unmarshal.go
serialization/bigint/unmarshal_utils.go
serialization/counter/marshal_utils.go
serialization/counter/unmarshal.go
serialization/counter/unmarshal_utils.go
serialization/cqlint/marshal_utils.go
serialization/cqlint/unmarshal.go
serialization/cqlint/unmarshal_utils.go
serialization/smallint/marshal_utils.go
serialization/smallint/unmarshal.go
serialization/smallint/unmarshal_utils.go
serialization/tinyint/marshal_utils.go
serialization/tinyint/unmarshal.go
serialization/tinyint/unmarshal_utils.go

Added for `smallint`, `int`, `bigint`, `counter` `cql types`.
Additional fixed `errors text` for `tinyint` `cql type`

Fix unmarshall errors, add condition for `nil reference`

---

marshal.go
marshal_test.go
serialization/float/marshal.go
serialization/float/marshal_utils.go
serialization/float/unmarshal.go
serialization/float/unmarshal_utils.go
tests/serialization/marshal_8_float_corrupt_test.go
tests/serialization/marshal_8_float_test.go

Changes:
1. On unmarshall data which length different from 0 or 4 was `no error` before, now return an error.
2. Optimized marshal, unmarshall functions.

Fix `float` marshal, unmarshall functions

---

internal/tests/serialization/mod/custom.go
internal/tests/serialization/utils_str.go
marshal.go
tests/serialization/marshal_20_map_v2_corrupt_test.go
tests/serialization/marshal_20_map_v2_test.go
tests/serialization/marshal_20_map_v3_corrupt_test.go
tests/serialization/marshal_20_map_v3_test.go

Changes:
1. Added marshal tests for `list`, `set` `cql types`
2. Added `gocql.NewCollectionType` function to create `CollectionType`
3. Added `custom types` for `map[int32]int32`,`map[int32]*int32` into `mod` package
4. Makes it so, if the `value string` out of print limit, then `value string` include only `value type`

Add `map` marshal tests

---

marshal.go
marshal_test.go
serialization/double/marshal.go
serialization/double/marshal_utils.go
serialization/double/unmarshal.go
serialization/double/unmarshal_utils.go
tests/serialization/marshal_9_double_corrupt_test.go
tests/serialization/marshal_9_duble_test.go

Changes:
1. On unmarshall data which length different from 0 or 8 was `no error` before, now return an error.
2. Optimized marshal, unmarshall functions.

Fix `double` marshal, unmarshall functions

---

serialization/smallint/marshal_utils.go
serialization/smallint/unmarshal_utils.go

Changes:
Marshal functions:
* unnecessary value type conversion has been removed.
* unnecessary dereference has been removed.
* removed unnecessary value checks for `reflect.Int8`,`reflect.Int16`,`reflect.Uint8`,`reflect.Uint16` kinds
* makes the right value type in the error of the `EncReflect` function
Unmarshal functions:
* unnecessary value type conversion has been removed.
* redo the functions for the double references values.
* the condition `data == nil` moved after the condition `len(data)==0` in the functions of the double references values.

Fix marshal `smallint` - optimization

---

conn.go
host_source.go

https://github.com/scylladb/scylladb/pull/19684 brings possibility of having nodes coordinator-only nodes (or zero-token nodes). So now there is a possibility of having hosts with no tokens. We do not want to throw a warning when such scenario occurs. But also we do not want to send requests to such a node.
Refs: https://github.com/scylladb/gocql/issues/226

Do not throw a warning for zero token nodes

---

serialization/cqlint/marshal_utils.go
serialization/cqlint/unmarshal_utils.go

Changes:
Marshal functions:
* unnecessary value type conversion has been removed.
* unnecessary dereference has been removed.
* removed unnecessary value checks for `reflect.Int8`, `reflect.Int16`, `reflect.Int32`, `reflect.Uint8`, `reflect.Uint16`, `reflect.Uint32` kinds
* makes the right value type in the error of the `EncReflect` function
Unmarshal functions:
* unnecessary value type conversion has been removed.
* redo the functions for the double references values.
* the condition `data == nil` moved after the condition `len(data)==0` in the functions of the double references values.

Fix marshal `cqlint` - optimization

---

README.md

I was looking after the Data Types cheatsheet and after a while I found at [GoCQLX Example file](https://github.com/scylladb/gocqlx/blob/ab73391f35174a29624a55cb9cfdbc059ae302e2/example_test.go#L176). IMHO this information should be more straightforward as possible.
Also added an "Quick Start" section to give some orientation for a driver newcomer to see it run ASAP.
* Added a "Quick Start" section with instructions on how to spawn a ScyllaDB instance using Docker and create a new connection using ScyllaDB GoCQL. (`README.md`)
* Introduced a "Data Types" section listing all ScyllaDB types reflected in the GoCQL environment along with their corresponding Go types. (`README.md`)

docs: add data types and quick start

---

.github/workflows/extended-ci-longevity-large-partitions-with-network-nemesis-1h-test.yml

This workflow pushes scylla-bench docker image using gocql version from the PR and triggers jenkins job that uses this image of scylla-bench.

Add github workflow running jenkins job

---

host_source.go
host_source_test.go

To ensure that driver handles zero-token nodes properly we need to make sure that following scenarios work as intended:
`datacenter2` is a zero-token datacenter
target host - host you feed to `NewCluster`
target dc - dc name you feed to `DCAwareRoundRobinPolicy`
1. `target host` = `any host from datacenter1`, `target dc` = `datacenter1`. It should succeed, you should be able to execute queries
2. `target host` = `any host from datacenter2`, `target dc` = `datacenter1`. It should succeed, you should be able to execute queries
3. `target host` = `any host from datacenter1`, `target dc` = `datacenter2`. It should fail with error
4. `target host` = `any host from datacenter2`, `target dc` = `datacenter2`. It should fail with error
This PR is needed for scenario 4 to work properly.

Check if localHost is not zero token node

---

debounce/simple_debouncer_test.go

Reason - sometimes this test panics, this leads to problems with the pipelines.
So, i suggest skipping the `TestSimpleDebouncer` test before solving the problem with `debounce`, to not create problems for other PRs.

Fix `debounce` add skipping the `TestSimpleDebouncer` test

---

conn.go
conn_test.go

Previously when node was zero-token type we did not consider it in schema agreement process. 
This PR fixes that.

Wait for zero-token nodes in schema agreement

---

host_source.go
host_source_test.go

To make `ringDescriber` behavior around zero-token nodes testable getting peers information from the query result needs to be moved to separate function.
Fixes: #338

Move getting peers information to separate function

---

marshal.go
serialization/bigint/marshal_utils.go
serialization/blob/marshal_utils.go
serialization/counter/marshal_utils.go
serialization/cqlint/marshal_utils.go
serialization/double/marshal_utils.go
serialization/float/marshal_utils.go
serialization/smallint/marshal_utils.go
serialization/text/marshal_utils.go
serialization/timeuuid/marshal_utils.go
serialization/tinyint/marshal_utils.go
serialization/uuid/marshal_utils.go
serialization/varchar/marshal_utils.go
tests/serialization/marshal_0_unset_test.go

Changes:
* fix `gocql.Marshal` add the `unsetColumn` processing before the `cql types` processing

Fix `gocql.Marshal` add the `unsetColumn` processing

---

serialization/ascii/marshal_utils.go

Add `unsetColumn` processing for `ascii` `cqltype`.
Close #354

Fix marshal `ascii`, add `unsetColumn` processing

---

conn.go
connectionpool.go
events.go
host_source.go
metadata_scylla.go
policies.go
ring.go
scylla.go
session.go
tablet_test.go

Add tablets invalidation in case node is removed or keyspace/table is dropped/updated.
Fixes: #350

Invalidate tablets data

---

.github/workflows/extended-ci-longevity-large-partitions-with-network-nemesis-1h-test.yml

Previously branch name was used, but it didn't work if the branch name had '/' character.
Fixes: #358

Use commit SHA instead of branch name in extended-ci

---

metadata_scylla.go

Invalidate tablets of updated keyspace/table on control connection reconnect

---

marshal.go
marshal_test.go
serialization/inet/marshal.go
serialization/inet/marshal_utils.go
serialization/inet/unmarshal.go
serialization/inet/unmarshal_utils.go
tests/serialization/marshal_14_inet_corrupt_test.go
tests/serialization/marshal_14_inet_test.go

Changes:
1. Marshaling `out of the bounds` `net.IP` values does not return an error before, now returns an error.
2. Unmarshalling `out of the bounds` data into `string` and `*string` does not return an error before, now returns an error.
3. Marshaling and unmarshalling `[]byte{}`, `[4]byte{}`, `[16]byte{}` and `custom types` of these types and `custom string` was unsupported before, now is supported.
4. Unmarshalling `zero` and `nil` data into `net.IP` and `string` was unsupported before, now is supported.

Fix `inet` marshal, unmarshall functions

---

serialization/varint/marshal_bigint_test.go
serialization/varint/marshal_custom.go
serialization/varint/marshal_ints.go
serialization/varint/marshal_utils.go

This change is necessary to use the `encInt64` function in the `decimal` package to marshaling.

Fix `varint`, makes `encInt64` function exportable

---

internal/tests/serialization/utils_equal.go
marshal.go
marshal_test.go
serialization/decimal/marshal.go
serialization/decimal/marshal_utils.go
serialization/decimal/unmarshal.go
serialization/decimal/unmarshal_ints.go
serialization/decimal/unmarshal_utils.go
serialization/varint/marshal_bigint_test.go
serialization/varint/marshal_custom.go
serialization/varint/marshal_ints.go
serialization/varint/marshal_utils.go
tests/serialization/marshal_10_decimal_corrupt_test.go
tests/serialization/marshal_10_decimal_test.go

Changes:
1. Marshallig and Unmarshalling are `string` and `custom string`, was unsupported before, now is supported.
3. Unmarshalling `zero data` and `nil data` into `inf.Dec{}`, was unsupported before, now is supported.

Fix `decimal` marshal, unmarshall functions

---

marshal.go
marshal_test.go
serialization/cqltime/marshal.go
serialization/cqltime/marshal_utils.go
serialization/cqltime/unmarshal.go
serialization/cqltime/unmarshal_utils.go
tests/serialization/marshal_15_time_corrupt_test.go
tests/serialization/marshal_15_time_test.go

Changes:
1. Marshallig `out of range values` does not return an error before, now returns an error.
2. Unmarshalling `corrupted data` and `out of range data` does not return an error before, now returns an error.

Fix `time` marshal, unmarshall functions

---

marshal.go
marshal_test.go
serialization/timestamp/marshal.go
serialization/timestamp/marshal_utils.go
serialization/timestamp/unmarshal.go
serialization/timestamp/unmarshal_utils.go
tests/serialization/marshal_16_timestamp_corrupt_test.go
tests/serialization/marshal_16_timestamp_test.go

Changes:
1. Unmarshalling `nil data` and `zero data` into `time.Time{}`return a `negative value` before, now returns a `zero value`.
3. Unmarshalling `corrupted data` does not return an error before, now returns an error.

Fix `timestamp` marshal, unmarshall

---

cassandra_test.go
serialization/timestamp/marshal_utils.go
serialization/timestamp/unmarshal_utils.go
tests/serialization/marshal_16_timestamp_corrupt_test.go
tests/serialization/marshal_16_timestamp_test.go

Changes:
1) Unmarshalling `zero data` into `time.Time` return `time.Time{}` before, now returns `zeroTimestamp`
2) Marshalling the `0001-1-1T00:00:00Z` value of the `time.Time` return `zero data` before, now returns a data that is equivalent to the difference between `0001-1-1T00:00:00Z` and `1970-1-1T00:00:00Z`
3) Added range matching check for the `time.Time` on marshalling and relevant tests.

Fix `timestamp` serialization into `time.Time`,  makes `zero data` <-> `zeroTimestamp`

---

marshal.go
marshal_test.go
serialization/boolean/marshal.go
serialization/boolean/marshal_utils.go
serialization/boolean/unmarshal.go
serialization/boolean/unmarshal_utils.go
tests/serialization/marshal_1_boolean_corrupt_test.go
tests/serialization/marshal_1_boolean_test.go

Changes:
1. Unmarshalling `big data` does not return an error before, now returns an error.

Fix `boolean`, marshal, unmarshall functions

---

marshal.go
marshal_test.go
serialization/duration/duration.go
serialization/duration/marshal.go
serialization/duration/marshal_utils.go
serialization/duration/marshal_vint_test.go
serialization/duration/unmarshal.go
serialization/duration/unmarshal_utils.go
serialization/duration/unmarshal_vint_test.go
tests/serialization/marshal_18_duration_corrupt_test.go
tests/serialization/marshal_18_duration_test.go

Changes:
1. Unmarshalling into `int64`, `custom int64`, `time.Duration`, `string` and `custom string` was unsupported before, now is supported.
2. Marshalling are `custom string`, `custom int64` was unsupported before, now is supported.
3. Unmarshalling `broken data` does not return an error before, now returns an error.
4. Unmarshalling `big data` does not return an error before, now returns an error.

Fix `duration` marshal, unmarshall functions

---

conn.go
conn_test.go
errors_test.go
policies.go
query_executor.go

This PR:
* Makes Conn.exec to include a flag into error that signals that query could have been actually executed, despite error been recieved.
* Picks up this error in queryExecutor.do and if query is not idempotent wrap it with user-facing error that would signal to retry policy and to user that this non idempotent query was failed but could be actually executed.
Fixes: #326, #331

Let retry policy to decide about non idempotent queries

---

cluster.go
session.go
session_test.go

Idea is the following:
* You create cluster configuration
* You create session of it that does not actually connects to the cluster, but rather just starting this proccess.
* If you are trying to execute query on such session, if it is not ready yeat it will throw you an NotReady error
* Have an API that allows you to know if session is ready to execute queries
Fixes: #234

Make it possible for NewSession not to block

---

serialization/cqlint/unmarshal_utils.go
serialization/smallint/unmarshal_utils.go
serialization/tinyint/unmarshal_utils.go
serialization/varint/unmarshal_ints.go

Change: added const for negative integers in unmarshall functions in packages `tinyint`,`smallint`,`cqlint`,`varint`.
Closes the issue #327

Fix unmarshall, make const for negative ints

---

cluster.go
conn.go
session.go
warning_handler.go

Time to time server provides usefull information in warnings.
Almost all drivers print it out, we need to make gocql do the same.

Make driver print warnings returned by server

---

integration_serialization_scylla_test.go
internal/tests/serialization/valcases/get.go
internal/tests/serialization/valcases/simple.go
marshal.go
serialization/duration/marshal_utils.go
serialization/timeuuid/marshal_utils.go
serialization/timeuuid/unmarshal_utils.go
tests/serialization/marshal_13_uuids_test.go
tests/serialization/marshal_14_inet_test.go
tests/serialization/marshal_17_date_test.go
tests/serialization/marshal_18_duration_test.go
tests/serialization/marshal_8_float_test.go
tests/serialization/marshal_9_duble_test.go

Changes:
1) Added serialization tests for `cql simple types`. The `counter` type is not included. 
2) Fixed `timeuuid`. Marshaling `zeroUUID` returns `make([]byte,16)` before, now returns `make([]byte,0)`
3) Added values test cases for `uuid`, `timeuuid`, `inet`, `float`, `double` `cql types` into `unit tests`.
Here are the contents of the tables selected by `cqlsh`:
`test_ascii`:
```
test_id | test_col
---------+-------------
val | test string
nil |        null
zeros | 
```
`test_bigint`:
```
test_id | test_col
---------+----------------------
min | -9223372036854775808
nil |                 null
zeros |                    0
+1 |                    1
-1 |                   -1
max |  9223372036854775807
```
`test_blob`:
```
test_id | test_col
---------+--------------------------
val | …
```

Add `scylla` serialization tests

---

cloud_cluster_test.go
docker-compose.yml
events_ccm_test.go
ring_describer.go

Full scan queries are slower even when there is only one record
Fixes: https://github.com/scylladb/gocql/issues/389

Fix every query to system.local to have WHERE clause

---

cassandra_test.go
common_test.go

Call createKeyspace separately in both versions of createSessionFromCluster

---

cluster.go

Fixes: https://github.com/scylladb/gocql/issues/392
RFC: https://datatracker.ietf.org/doc/html/rfc5077
Enables TLS session ticket cache by default.

tls: enable session ticket cache by default

---

ring_describer_test.go

There are two test with same name, which can cause `go test` to fail

Rename TestMockGetHostsFromSystem from ring_describer_test.go

---

conn.go
conn_test.go

Currently schema agreement queries pull columns that are not used. In scenarios with big number of nodes it causes cluster and driver being slow.
This commit makes schema agreement code pull only columns that are used.
Fixes: https://github.com/scylladb/gocql/issues/408

Optimise schema agreement queries

---

CONTRIBUTING.md
NOTICE
cassandra_test.go
common_test.go
conn_test.go
policies.go
session_test.go

Original commit list:
**1. Commit: https://github.com/apache/cassandra-gocql-driver/commit/253be521e1142cf4f0ef8fe30310c4e7675715f2**
Message: 
```
Add Bogdan-Ciprian Rusu as agreed to donate contributions to ASF
ref: https://github.com/apache/cassandra-gocql-driver/issues/1751#issuecomment-2370352287
patch by Mick Semb Wever; reviewed by João Reis for CASSANDRA-19723
```
Status: `APPLIED`
**2. Commit: https://github.com/apache/cassandra-gocql-driver/commit/47886e5b59559ed1fde9c48363fbe4be352fe76b** 
Message: 
```
Update CONTRIBUTING.md
The section for the commit message format is too generic,
so this commit adds more details and a clear example of
how a commit message should be structured.
This commit also makes it clear in CONTRIBUTING.md that
JIRA should be used instead of GH issues …
```

Merge upstream changes up to commit '280f0aa2'

---

internal/tests/serialization/valcases/simple.go
serialization/duration/duration.go
serialization/duration/marshal_str.go
serialization/duration/marshal_str_test.go
serialization/duration/marshal_utils.go
serialization/duration/unmarshal_str.go
serialization/duration/unmarshal_str_test.go
serialization/duration/unmarshal_utils.go
tests/serialization/marshal_18_duration_corrupt_test.go
tests/serialization/marshal_18_duration_test.go

Marshalling and unmarshalling  `string` and `custom string` `go types` was done using the "time" package before, months and days was unsupported.
Now marshalling and unmarshalling  `string` and `custom string` with months and days is supported.

fix `duration` makes `string` marshal, unmarshal in the full range

---

cluster.go
filters.go
filters_test.go
host_source.go
host_source_test.go
hostpolicy/hostpool.go
hostpolicy/hostpool_test.go
policies.go
policies_test.go

Original commit list:
**1. https://github.com/apache/cassandra-gocql-driver/commit/fb11fadaf4e42b57d2b4186052ec7fc40c77aafe**
Message:
```
Remove HostPoolHostPolicy from gocql package
HostPoolHostPolicy was moved to a separate package, and users don't need to download dependency if they aren't using it.
patch by Oleksandr Luzhniy; reviewed by João Reis, Stanislav Bychkov, James Hartig, for CASSGO-21
```
Status: `APPLIED`
**2. https://github.com/apache/cassandra-gocql-driver/commit/cb139a396ee9ac76fdcd5fcddfeaafd877578bb1**
Message:
```
standardize datacenter spelling
This change keeps the repo internally consistent in the spelling of "datacenter". The public interface is kept to prevent breakage.
Patch by Brendan Gerrity; reviewed by João Reis, James Hartig for CASSGO-35
```
Status: …

Merge upstream changes up to commit  `4ad747972`

---

conn.go
control.go
host_source.go
metadata_scylla.go

Original commit list:
**1. https://github.com/apache/cassandra-gocql-driver/commit/f3d13d4d0bf4e4cee186a47ed5a2c5e5a7fe3e54**
Message:
```
Add support for cassandra 4.0 table options
In the PR implemented backward compatibility with previous versions,
and added new types support. To make metadata table support easier for
future Cassandra versions, hardcode scan from Cassandra were replaced
with new "parseSystemSchemaViews" method which is much easier to expand,
even if some fields were added in the middle of the table it wouldn`t be an issue anymore.
patch by Mykyta Oleksiienko; reviewed by Joao Reis and James Harting CASSGO-13
```
Status: `APPLIED`
**2. https://github.com/apache/cassandra-gocql-driver/commit/65e2cafa8c46534a1aef83d5483302d23f7cb792**
Message:
```
Refactor HostInfo …
```

Merge upstream changes up to commit  `f35d4637` 

---

frame.go

Splits all `append` operations in one

<framer> optimization `writeHeader(...)`

---

cassandra_test.go
cluster.go
connectionpool.go
frame.go
policies.go
policies_integration_test.go
query_executor.go
session.go

Original commit list:
**1. https://github.com/apache/cassandra-gocql-driver/commit/bf16ec371974a1c2082d525b6d78fac108f8c49b**
Message:
```
CASSGO-4 Support of sending queries to the specific node
Query.SetHostID() allows users to specify on which node the Query will be executed.
It is not a tipycal use case, but it makes sense with virtual tables which are available since C* 4.0.
Patch by Bohdan Siryk; Reviewed by João Reis, James Hartig for CASSGO-4
```
Status: `APPLIED`
**There is a problem with hanging in the `(q *queryExecutor) do(...)` function, needs to be discussed**
**2. https://github.com/apache/cassandra-gocql-driver/commit/0aa180badfc90b8c3f1f4e4d2da457aef00e280b**
Message:
```
CASSGO-26 consistency serial was added
The user should be able to set consistency to SERIAL or …
```

Merge upstream changes up to commit  `0aa180bad`

---

cluster.go
conn_test.go
control.go
control_test.go
exec.go
filters.go
helpers.go
session.go

It will allow to override default DNSResolver, whether for testing purposes or user convenience.
All behavior preserved.

Add `DNSResolver` to Cluster config

---

session.go

Query and Batch could be reused, reexecuted.
Since metrics are stored on Query/Batch side new execution gets metrics from prior executions.
As result, attempts are inherited from prior execution and lead to having no retry on next execution.
Fixes: https://github.com/scylladb/gocql/issues/438

Reset query metrics for both Batch and Query

---

common_test.go
conn_test.go
control.go
control_test.go
dial.go
dns_test.go
exec.go
filters.go
host_source.go
scylla.go
scylla_shard_aware_port_common_test.go
session.go

Add DNS tests that covers basic cases:
1. Record per node
2. Record per cluster
3. Record per cluster with first record pointing to a broken node
Plus add tests with `AddressTranslator`
Problems fixed:
1. Remove all hostname usage, before this change driver would resolve hostname when connecting to the node, it led to problems with one dns record relates to the whole cluster.
2. Apply address translator to resolved nodes, before that it was not done, as result, if addressTranslator is configured it would be skipped for initial nodes and ip addresses that driver picks up from the dns.

Add DNS tests suite and fix problem it found

---

query_executor.go

If on any retry this flag become true, it should stay true.
follow up by test issue: https://github.com/scylladb/gocql/issues/453

Fix calculation of potential executed flag

---

policies.go

`tokenAwareHostPolicy.updateReplicas` go through the whole cycle eve if there is nothing to be done.
Move nil check to begging of the method.
Also check if keyspace is empty, in all these cases keep `replicas` untouched.

Optimize tokenAwareHostPolicy.updateReplicas

---

policies.go

Switching to less loaded replica for LWT will only increase LWT congestion. 
As quick solution it is better to use slow replica anyways. 
Better solution should be synchronized between clietns so that all clients would start avoid slow replica all at the same time.

Disable avoiding slow replica for LWT queries

---

conn.go
events.go
host_source.go
metadata_scylla.go

Changes to metadataDescriber:
1. Removed unnecessary lock from `getSchema`
2. Removed unnecessary lock from `clearSchema`
3. Split the tablets API into internal and external parts; moved the lock from internal to external
4. Fixed error matching in `refreshAllSchema`
These changes collectively eliminate the possibility of a deadlock on `metadataDescriber.mu`.
Previously, when a query executed on a keyspace with tablets enabled, any schema update could lead to a deadlock.
To be followed by: https://github.com/scylladb/gocql/issues/451
Fixes: https://github.com/scylladb/gocql/issues/444

Fix metedata describer deadlock

---

policies.go
policies_integration_test.go
session.go

Token aware policy is not properly initialized, cluster metadata if effectively empty right after session is being created.
Following fixes:
1. Initialize `Session.useSystemSchema` early
2. Change `getKeyspaceMetadata` to make it possible read keyspace metadata when session is not fully initialized
3. Run `SetPartitioner` after `Session.useSystemSchema` is initialized to enable it's proper handling

Fix token aware policy initialization

---

common_test.go
control_integration_test.go
integration.sh

To make it possible to work with the cluster deployed via CCM we need to make socket file be configurable.

Add socket file path cli option

---

common_test.go
recreate_test.go
tablet_integration_test.go

There are three types of tests in regards of the tablts feature:
1. That tablet agnostict. Will work despite the feature.
2. That needs tablets. Need tablets and don't work otherwise.
3. Need some tuning to work with tablets, like ks have to be created in particular way
All these tests need to be aware if server supports tablets or not. This commit makes them aware of the feature and make test work or skip.

Make tests aware of whether tablets are supported by server

---

conn.go
metadata_scylla.go
policies.go
scylla.go
tablet_test.go
tablets.go

Since `HostInfo.hostID` is a string, in all cases when driver address `ReplicaInfo.hostId` it converts UUID to a string. 
Which is unnecessary, let's store them in the same type. 
Later we can optimize it by storing it as `gocql.UUID` or `google/uuid`.
Related to: https://github.com/scylladb/gocql/issues/469

Tablets: use string in `ReplicaInfo.hostId`

---

policies.go
scylla.go
tablet_test.go
tablets.go

Two purposes:
1. It speeds up lookup operation. Due to having no interface casting
2. It decouples API from `gocql` package and enables it to be relocated to another package
Related to: https://github.com/scylladb/gocql/issues/469 and https://github.com/scylladb/gocql/issues/470

Tablets: switch lookup API to use int64 instead of gocql.Token

---

common_test.go

Two changes:
1. Fix description of `-cluster-socket`
2. Fix `isTabletsAutoEnabled` to be case insensitive

Tests: fix tablets auto enabled detection

---

conn.go

Table name for it is wrong, `system.peers_2` instead of `system.peers_v2` and `rpc_address` is used instead of `preferred_ip`

Fix usage of cassandra-specific `system.peers_v2` table

---

address_translators_test.go
cassandra_test.go
cluster_test.go
common_test.go
integration_test.go
internal/tests/common.go
keyspace_table_test.go
policies_test.go
ring_describer_test.go
schema_queries_test.go
tablet_test.go

It will allow to reuse them outside of `gocql` package, in particular for tablets tests
Related to: https://github.com/scylladb/gocql/issues/470

Tests: relocate assert functions to the test package

---

metadata_scylla.go
policies.go
scylla.go
session.go
tablets/tablets.go
tablets/tablets_test.go

List of changes:
1. Move all logic that reads and writes tablets to `CowTabletList`
2. Remove `metadataDescriber` lock in front of tablets API
3. Remove tablets initialization from `Session.init`
4. Fix `scyllaConnPicker.Pick` to stop iterating when shard is found
5. Drop rw lock from `CowTabletList` in favor of `atomic.Value`
6. Add write lock to `CowTabletList` to ensure there is only one write operation running in parallel
Final fix for: https://github.com/scylladb/gocql/issues/469

Tablets more small optimizations

---

.github/workflows/main.yml

Remove extra cache step, `actions/setup-go@v5` is already support caching by default.

cicd: remove extra cache step

---

session.go

After session is closed, it is still could be used by event handlers. So, reseting policy will lead to following error:
```
github.com/gocql/gocql.(*tokenAwareHostPolicy).updateReplicas(0xc0004c2180, 0xc00039f830, {0xc00002ade0, 0x1b})
/home/runner/work/gocql/gocql/policies.go:600 +0x90
github.com/gocql/gocql.(*tokenAwareHostPolicy).KeyspaceChanged(0xc0004c2180, {{0xc00002ade0?, 0x2000107?}, {0xc0004d1090?, 0xffffffffffffffff?}})
/home/runner/work/gocql/gocql/policies.go:587 +0xb3
github.com/gocql/gocql.(*Session).handleKeyspaceChange(0xc0000f4408, {0xc00002ade0, 0x1b}, {0xc0004d1090, 0x7})
/home/runner/work/gocql/gocql/events.go:157 +0xe2
github.com/gocql/gocql.(*Session).handleSchemaEvent(0xc0000f4408, {0xc00039ed70?, 0xc0002848c0?, 0x30d40?})
/home/runner/work/gocql/gocql/events.go:138 …
```

fix: possible panic on session.Close

---

.github/workflows/main.yml
Makefile
testdata/pki/generate_certs.sh
tests/bench/go.sum

CICD can fail on PKI creation due to lack of file this script wants to delete.
Make it ignore if file is not there.

cicd: unit tests step more stable

---

cassandra_test.go
conn_test.go
recreate_test.go
session.go

Since this driver mostly targets scylla,
it would be better to enable it by default.
Fixes: https://github.com/scylladb/gocql/issues/481

Use TokenAwarePolicy by default

---

conn.go

ApplicationInfo interface allows to write any value. 
We need to make sure it does not override any system values from startup options.

fix startup logic to make sure ApplicationInfo.UpdateStartupOptions does not override

---

.github/workflows/extended-ci-longevity-large-partitions-with-network-nemesis-1h-test.yml

Currently patterns are outdated and pull `2024.1.x` and old `6.1.x` images. 
Let's relax them to pull what they suppose to pull

cicd: update get version step to pull new images

---

control.go
integration_test.go

When `ringDescriber.GetHostsFromSystem` reading `system.peers` on connection from the control connection that have `controlConn.HandleError` in the `errorHandler`. This `controlConn.HandleError` calls `controlConn.reconnect` which calls `controlConn.attemptReconnect` which calls `ringDescriber.getHostsList`. When it happens `ringDescriber.GetHostsFromSystem` call is already obtained `r.mu.Lock()` on `ringDescriber`, and `ringDescriber.getHostsList` will request same lock via `r.mu.RLock()`, as result `Session` will deadlock.
To address that we need to separate context between two locks, best place for it is to call `controlConn.reconnect` on the background in `controlConn.HandleError`.
Fix: https://github.com/scylladb/gocql/issues/521

Run control connection reconnect in background

---

marshal.go
scylla.go

In some parts of the code one type can have receivers with different names.
It is not a bug, but better to fix it, if we go for better linting it will pop up.

Align receivers

---

cluster.go
conn.go
connectionpool.go
integration_test.go

Driver uses `ClusterConfig.Timeout` as reading timeout for socket operations on connection.
When socket operations fails, driver considers such connection as faulty and will close it.
In low latency use case, when users set `ClusterConfig.Timeout` to low values, it can result in having unstable connection. To address this issue and have more granular control over driver behavior we need to introduce another configuration option that controls socket reading timeout.

Introduce ClusterConfig.ReadTimeout

---

.golangci.yml
address_translators_test.go
cloud_cluster_test.go
cluster_test.go
integration_serialization_scylla_test.go
internal/tests/err_equal.go
keyspace_table_test.go
policies_test.go
schema_queries_test.go
scyllacloud/config_test.go
scyllacloud/hostdialer_test.go
tests/bench/go.sum
tuple_test.go

All tests reside in files that require `unit` or `integration` tag:
```
//go:build integration
// +build integration
```
Since these tags was not provided to golangci, it did not check test code.
This commit:
1. Makes it work for tests
2. Addresses linting problems it found

Make golangci work for test code

---

.github/workflows/docs-pages.yml
.github/workflows/docs-pr.yml
docs/Makefile
docs/pyproject.toml

Target: cache dependencies both for pip and poetry 
`setup-python` poetry cache feature requires poetry to be installed before `setup-python`.
Which means that:
1. We will have `Install poetry` before `setup-python` and after, which looks awkward.
2.  `poetry` as pip dependency will not be cached
That is why `actions/cache` was used instead.
To make caching properly work I made `docs/pyproject.toml` to be source of truth for `poetry` and `python versions` and calculated cache hash from `docs/pyproject.toml` and `docs/Makefile`

Enable cache on docs workflows

---

.github/workflows/main.yml

Enable cache on PR workflows for:
1. For pip pacakges (for CCM)
2. For Scylla CCM images
3. For Cassandra CCM images

Enable cache on PR workflow

---

metadata_scylla.go

When using scylladb/gocql with upstream Cassandra, the driver queries system_schema.tables to get
table metadata.
When using scylladb/gocql with ScyllaDB, the
driver should also query system_schema.scylla_tables.
Closes https://github.com/scylladb/gocql/issues/579

Conditionally query scylla_tables for table metadata
